config/routes.rb
Moneysave::Application.routes.draw do
  get "csv_import/index", as: :csv_import
  post "csv_import/upload", as: :csv_import_upload

  devise_for :users
  root 'entries#index'

  resources :budgets do
    collection do
      get :autocomplete
    end
  end

  resources :entries

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  
  belongs_to :user
  has_and_belongs_to_many :entries

  def for_month(date)
    entries.for_month(date)
  end

  def sum_for_month(date)
    @sum_for_month ||= for_month(date)
                        .for_budget(self)
                        .map {|entry| entry.amount }
                        .reduce(0, :+).to_f
  end

  def excedded_for_month(date)
    sum_for_month(date) > amount
  end

  def month_percentage(date)
    amount > 0 ? (sum_for_month(date) / amount) * 100 : 0.0
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  default_scope { order('entries.date ASC') }

  TYPES = %w{income expense}

  validates :amount, presence: true
  validates :date, presence: true
  validates :entry_type, inclusion: { in: TYPES }

  belongs_to :user
  has_and_belongs_to_many :budgets

  def initialize(data = {})
    super(data)
    self.entry_type = "expense"
  end

  def self.for_month(date)
    where("date >= ? AND date <= ?", date.at_beginning_of_month, date.at_end_of_month)
  end

  def self.for_budget(budget)
    joins(:budgets).where("budgets_entries.budget_id = #{budget.id}")
  end

  def self.total_for_month(date)
    for_month(date).map(&:amount).reduce(0, :+)
  end

  def unique?
    Entry.where(amount: amount, date: date, user: user).count == 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable

  has_many :budgets
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = current_user.budgets
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    @date = Date.parse(params[:date])
    @entries = @budget.entries.for_month(@date)
  end

  # GET /budgets/new
  def new
    @budget = current_user.budgets.build
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = current_user.budgets.build(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to budgets_path, notice: 'Budget was successfully created.' }
        format.json { render action: 'show', status: :created, location: @budget }
      else
        format.html { render action: 'new' }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budgets_path, notice: 'Budget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url }
      format.json { head :no_content }
    end
  end

  def autocomplete
    term = params[:term]
    list = Budget.all.map {|b| b.description }.select{|e| e.downcase.include? term.downcase}

    respond_to do |format|
      format.json { render json: list }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget =  current_user.budgets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:description, :amount)
    end
end

app/controllers/csv_import_controller.rb
class CsvImportController < ApplicationController
  def index
  end

  def upload
    csv_file = params[:csv_file]

    if csv_file
      CSVImporterRBC.new.import(current_user, csv_file.read)
      flash[:notice] = "CSV Imported successfully"
    else
      flash[:notice] = "No CSV sent."
    end

    render :index
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_date, only: [:index]

  # GET /entries
  # GET /entries.json
  def index
    @entries = current_user.entries.for_month(@date)
    @budgets = current_user.budgets
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = current_user.entries.build
    @budgets = current_user.budgets
  end

  # GET /entries/1/edit
  def edit
    @budgets = current_user.budgets
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = current_user.entries.build(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entries_path, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entries_path, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = current_user.entries.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def entry_params
    if params[:entry][:budgets_list]
      budgets_list = params[:entry][:budgets_list].split(",")
      budgets = Budget.where(description: budgets_list)
      params[:entry][:budget_ids] = budgets.map(&:id)

      params[:entry].delete(:budgets_list)
    end

    params.require(:entry).permit!
  end

  def set_date
    if params[:date]
      @date = Date.parse(params[:date])
    else
      @date = Date.today
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/csv_import_helper.rb
module CsvImportHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/budgets/_form.html.erb
<%= form_for(@budget) do |f| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% @budget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<h1>Listing budgets</h1>

<p id="notice"><%= notice %></p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.description %></td>
        <td><%= number_to_currency(budget.amount) %></td>
        <td><%= link_to 'Show', budget, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render 'form' %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Budget: <%= @budget.description %> <small>Amount: <%= number_to_currency @budget.amount %> - Total: <%= number_to_currency @entries.sum("entries.amount") %></small></h3>

<%= render "entries/table" %>

app/views/csv_import/index.html.erb
<h1>CSV File Import</h1>

<% if flash[:notice].present? %>
  <div class="alert alert-info" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>


<%= form_tag csv_import_upload_path, multipart: true do%>
  <%= file_field_tag :csv_file %>
  <%= submit_tag "Process CSV", class: 'btn btn-sm btn-primary' %>
<% end -%>

app/views/entries/_budgets_summary.html.erb
  <div>
    <h3>Budgets Summary</h3>
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <td>Name</td>
          <td>Total</td>
          <td>Free</td>
          <td>Budget</td>
          <td></td>
        </tr>
      </thead>
      <tbody>
        <% @budgets.all.each do |budget| %>
        <tr>
          <!-- NAME -->
          <td><%= link_to budget.description, budget_path(budget, date: @date) %></td>
          <!-- Total -->
          <% if budget.sum_for_month(@date).zero? %>
            <td> <%= number_to_currency budget.sum_for_month(@date) %> </td>
          <% else %>
            <td class="<%= budget.excedded_for_month(@date) ? "danger" : "" %>"> <strong><%= number_to_currency budget.sum_for_month(@date) %></strong> </td>
          <% end -%>
          <!-- FREE -->
          <% if budget.excedded_for_month(@date) %>
            <td class="danger">
              <strong><%= number_to_currency(budget.amount - budget.sum_for_month(@date)) %></strong>
            </td>
          <% else %>
            <td><%= number_to_currency(budget.amount - budget.sum_for_month(@date)) %></td>
          <% end -%>
          <!-- BUDGET -->
          <td><%= number_to_currency budget.amount %></td>
          <!-- PERCENTAGE -->
          <td class="<%= budget.excedded_for_month(@date) ? "danger" : "" %>">
            %<%= "%.2f" % budget.month_percentage(@date) %>
          </td>
        </tr>
        <% end -%>
      </tbody>
      <tfoot class="secondary-text">
        <td>Total</td>
        <td><%= number_to_currency current_user.entries.total_for_month(@date) %></td>
        <td><%= number_to_currency(@budgets.sum(:amount) - current_user.entries.total_for_month(@date)) %></td>
        <td><%= number_to_currency @budgets.sum(:amount) %></td>
        <td>%0.00</td>
      </tfoot>
    </table>
  </div>

  <hr>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <label>Select budget</label>
    <% @budgets.all.each do |budget| %>
      <%= check_box_tag "entry[budget_ids][]", budget.id, @entry.budgets.include?(budget) %>
      <%= budget.description %> <br />
    <% end %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, value: @entry.date.try(:strftime, "%d/%m/%Y") %>
  </div>
  <div class="field">
    <%= f.label :entry_type %><br>
    <%= f.radio_button :entry_type, "expense" %> Expense &nbsp;
    <%= f.radio_button :entry_type, "income" %> Income
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $(function() {
    $("#entry_date").datepicker({todayBtn: true, autoclose: true, format: "dd/mm/yyyy"})
  })
</script>

app/views/entries/_table.html.erb
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>Date</th>
        <th>Budgets</th>
        <th>Type</th>
        <th>Amount</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @entries.preload(:budgets).each do |entry| %>
        <tr id="entry-<%= entry.id %>">
          <td><%= best_in_place entry, :description, as: :input, :display_with => lambda { |v| v.html_safe } %></td>
          <td><%= entry.date.strftime("%d/%b/%y") %></td>
          <td><input value="<%= entry.budgets.map {|b| b.description}.join(", ") %>" class="budget-tags" data-remote="entries/<%= entry.id %>.json"></td>
          <td><%= entry.entry_type %></td>
          <td> <strong><%= number_to_currency entry.amount %></strong> </td>
          <td><%= link_to 'Show', entry %></td>
          <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
          <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<%= render "budgets_summary" %>

<p id="notice"><%= notice %></p>

<div class="row-fluid">
  <h1>Listing entries</h1>

  <%= render "table" %>

  <br>

  <%= link_to 'New Entry', new_entry_path %>
</div>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @entry.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @entry.date %>
</p>

<p>
  <strong>Entry type:</strong>
  <%= @entry.entry_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @entry.amount %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moneysave</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div class="container">

    <div class="masthead">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Gimme Oro</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

              <li class="<%= request.path == entries_path ? 'active' : '' %>"><%= link_to "Entries", entries_path %></li>
              <li class="<%= request.path == budgets_path ? 'active' : '' %>"><%= link_to "Budgets", budgets_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="<%= request.path == csv_import_path ? 'active' : '' %>"><%= link_to "CSV Import", csv_import_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </div>
        </div><!--/.container-fluid -->
      </nav>


    </div>

    <% if @date %>
    <div>
      <h3><small><%= link_to "<<", entries_path(date: @date - 1.month) %></small>
          <span><%= @date.strftime "%B" %></span>
          <small><%= link_to ">>", entries_path(date: @date + 1.month) %></small></h3>
    </div>
    <% end -%>

    <%= yield %>

    <hr>

    <div class="footer">
      <p>© Bla bla bla 2014</p>
    </div>

  </div> <!-- /container -->

</body>
</html>